"""Generate canonical Unicode tables from the reference Python's Unicode database."""
import unicodedata as U
from pathlib import Path
import sys


def generate(path):
    decompositions, compositions, combining, whitespace = [], [], [], []
    for cp in range(0x110000):
        char = chr(cp)
        raw = U.decomposition(char)
        if raw and not raw.startswith("<"):
            parts = [int(p, 16) for p in raw.split()]
            if len(parts) > 2:
                raise ValueError("unexpected canonical decomposition")
            a, b = parts[0], parts[1] if len(parts) == 2 else 0
            decompositions.append((cp, a, b))
            if b and U.normalize("NFC", chr(a) + chr(b)) == char:
                compositions.append((a, b, cp))
        if U.combining(char):
            combining.append((cp, U.combining(char)))
        if char.isspace():
            whitespace.append(cp)
    lines = ["// Generated by scripts/generate-gocr-unicode.py; do not edit.",
             "#pragma once", f'constexpr char unicode_version[]="{U.unidata_version}";',
             "struct Decomposition { uint32_t cp, a, b; };",
             "constexpr Decomposition decompositions[]={"]
    lines += [f"    {{{cp},{a},{b}}}," for cp, a, b in decompositions]
    lines += ["};", "struct Composition { uint32_t a, b, cp; };",
              "constexpr Composition compositions[]={"]
    lines += [f"    {{{a},{b},{cp}}}," for a, b, cp in sorted(compositions)]
    lines += ["};", "struct Combining { uint32_t cp, value; };",
              "constexpr Combining combining[]={"]
    lines += [f"    {{{cp},{value}}}," for cp, value in combining]
    lines += ["};", "constexpr uint32_t whitespace[]={" +
              ",".join(map(str, whitespace)) + "};"]
    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    generate(sys.argv[1])
